"""
StreamGuard — DAG: SLA Report
Generates and emails a daily pipeline SLA report from Snowflake mart data.
"""

import logging
import os
import smtplib
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import snowflake.connector
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.utils.dates import days_ago

logger = logging.getLogger("streamguard.dag.sla_report")

default_args = {
    "owner": "streamguard",
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}


def generate_and_send_report(**context):
    conn = snowflake.connector.connect(
        account=os.getenv("SNOWFLAKE_ACCOUNT"),
        user=os.getenv("SNOWFLAKE_USER"),
        password=os.getenv("SNOWFLAKE_PASSWORD"),
        warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
        database=os.getenv("SNOWFLAKE_DATABASE"),
    )
    cursor = conn.cursor()

    # Yesterday's stats
    cursor.execute("""
        SELECT topic, total_records, anomaly_count, critical_anomalies,
               pipeline_sla_pct, avg_null_pct, schema_drift_events
        FROM MARTS.MART_PIPELINE_HEALTH
        WHERE stat_date = DATEADD('day', -1, CURRENT_DATE)
        ORDER BY topic
    """)
    rows = cursor.fetchall()
    conn.close()

    report_date = (datetime.utcnow() - timedelta(days=1)).strftime("%Y-%m-%d")
    rows_html = ""
    overall_sla = 0.0

    for r in rows:
        topic, records, anomalies, critical, sla, null_pct, drift = r
        overall_sla = max(overall_sla, float(sla or 0))
        color = "#d1fae5" if float(sla or 0) >= 99 else "#fef3c7" if float(sla or 0) >= 95 else "#fee2e2"
        rows_html += f"""
        <tr style="background:{color}">
            <td style="padding:8px;border:1px solid #ddd">{topic}</td>
            <td style="padding:8px;border:1px solid #ddd;text-align:right">{records:,}</td>
            <td style="padding:8px;border:1px solid #ddd;text-align:right">{anomalies}</td>
            <td style="padding:8px;border:1px solid #ddd;text-align:right">{critical}</td>
            <td style="padding:8px;border:1px solid #ddd;text-align:right"><b>{sla:.2f}%</b></td>
            <td style="padding:8px;border:1px solid #ddd;text-align:right">{null_pct:.2f}%</td>
            <td style="padding:8px;border:1px solid #ddd;text-align:right">{drift}</td>
        </tr>"""

    html_body = f"""
    <html><body style="font-family:Arial,sans-serif;color:#1f2937">
      <h2 style="color:#1B3A5C">StreamGuard — Daily Pipeline SLA Report</h2>
      <p><b>Date:</b> {report_date}</p>
      <table style="border-collapse:collapse;width:100%">
        <tr style="background:#1B3A5C;color:white">
          <th style="padding:10px;border:1px solid #ddd">Topic</th>
          <th style="padding:10px;border:1px solid #ddd">Records</th>
          <th style="padding:10px;border:1px solid #ddd">Anomalies</th>
          <th style="padding:10px;border:1px solid #ddd">Critical</th>
          <th style="padding:10px;border:1px solid #ddd">SLA %</th>
          <th style="padding:10px;border:1px solid #ddd">Avg Null %</th>
          <th style="padding:10px;border:1px solid #ddd">Schema Drifts</th>
        </tr>
        {rows_html}
      </table>
      <p style="color:#6b7280;font-size:12px">Generated by StreamGuard Observability Platform</p>
    </body></html>
    """

    # Send email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"StreamGuard SLA Report — {report_date}"
    msg["From"]    = os.getenv("SMTP_USER", "streamguard@example.com")
    msg["To"]      = os.getenv("ALERT_EMAIL", "admin@example.com")
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(os.getenv("SMTP_HOST", "smtp.gmail.com"),
                          int(os.getenv("SMTP_PORT", 587))) as server:
            server.starttls()
            server.login(os.getenv("SMTP_USER", ""), os.getenv("SMTP_PASSWORD", ""))
            server.send_message(msg)
        logger.info(f"SLA report sent for {report_date}")
    except Exception as e:
        logger.warning(f"Email send failed (non-fatal): {e}")

    return {"date": report_date, "topics": len(rows)}


with DAG(
    dag_id="dag_sla_report",
    default_args=default_args,
    description="Daily SLA email report",
    schedule_interval="0 8 * * *",   # 8 AM daily
    start_date=days_ago(1),
    catchup=False,
    tags=["streamguard", "reporting"],
) as dag:

    PythonOperator(
        task_id="generate_and_send_report",
        python_callable=generate_and_send_report,
        provide_context=True,
    )
